import requests
from database import *
from icalendar import Calendar, Event

d = DatabaseManager()
r = requests.get("http://www.ucl.ac.uk/timetable/ics/spxipmlh28sgtpd")

cal = Calendar.from_ical(r.text)

events_array = []

course_ids = []

for event in cal.walk():
	if event.get('SUMMARY'):

		event_name = event.get('SUMMARY').encode('utf-8')
		event_time = event.get('DTSTART').dt.time()
		event_date = event.get('DTSTART').dt.date()
		event_description = event.get('DESCRIPTION')
		course_id = event.get('UID').split('.')[1]

		if not [course_id,event_name] in course_ids:
			course_ids.append([])
			# course id is generated by ucl
			# I have no fucking clue where it comes from
			# I pray to god it is unique
			course_ids[-1].append(course_id)
			course_ids[-1].append(event_name)

		events_array.append({
			'name': event_name,
			'time': event_time,
			'date': event_date,
			'description': event_description,
			'course_id': course_id
		})

ucl_to_us_dict = {}


for groups in course_ids:
	if not d.query('SELECT * FROM groups WHERE name=?', [groups[1]]):
		mygroupid = d.write_to_db('INSERT INTO groups (name, shortname) VALUES (?,?)', (groups[1], groups[1]))

		ucl_to_us_dict[groups[0]] = mygroupid
print ucl_to_us_dict

for event in events_array:
	if not d.query('SELECT * FROM events WHERE summary=?', [event.get('event_name')]):
		our_id = ucl_to_us_dict.get(event.get('course_id'))
		database_tuple = (our_id, str(event.get('date')), str(event.get('time')), event.get('name'))
		event[id] = d.write_to_db('INSERT INTO events (groupid, date, time, summary) VALUES (?,?,?,?)', database_tuple)



